# Generated by Django 3.2.15 on 2024-05-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20240528_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='created_at',
            new_name='updated_at',
        ),
    ]
