version: '3'
services:
  database:
    image: postgres:16.4
    container_name: star_burger_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network
    env_file:
      - ../.env
    ports:
      - 5432:5432
  
  frontend:
    image: star_burger_frontend
    container_name: star_burger_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    volumes:
      - assets:/opt/star-burger/assets
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir assets --public-url="./"
    networks:
      - app-network
  
  backend:
    image: star_burger_backend
    container_name: star_burger_backend
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    volumes:
      - assets:/opt/star-burger/assets
      - media:/opt/star-burger/media
    env_file:
      - ../.env
    ports:
      - 8000:8000
    command: python manage.py runserver 0:8000
    depends_on:
      - database
      - frontend
    networks:
      - app-network

volumes:
  postgres_data: 
  assets:
  media:

networks:
  app-network:
    driver: bridge
    