# Generated by Django 3.2.15 on 2024-05-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20240524_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Не обработан', 'Не обработан'), ('Сборка', 'Сборка'), ('Доставка', 'Доставка'), ('Доставлен', 'Доставлен')], db_index=True, default=('Не обработан', 'Не обработан'), max_length=50, verbose_name='статус'),
        ),
    ]
