# Generated by Django 3.2.15 on 2024-05-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Банковская карта', 'Банковская карта')], db_index=True, default='Банковская карта', max_length=50, verbose_name='Метод оплаты'),
        ),
    ]
