# Generated by Django 3.2.15 on 2024-05-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Создан'), ('2', 'Готовится'), ('3', 'Доставляется'), ('4', 'Завершён')], db_index=True, default='1', max_length=50, verbose_name='статус'),
        ),
    ]
