# Generated by Django 3.2.15 on 2024-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], db_index=True, default='card', max_length=50, verbose_name='Метод оплаты'),
        ),
    ]
