# Generated by Django 3.2.15 on 2024-05-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longtitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='долгота'),
        ),
    ]
