# Generated by Django 3.2.15 on 2024-06-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_created_at_place_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
