version: '3'
services:
  database:
    image: postgres:16.4
    container_name: star_burger_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network
    env_file:
      - ../.env
    ports:
      - 5432:5432
  
  frontend:
    image: star_burger_frontend
    container_name: star_burger_frontend
    build: ../frontend
    volumes:
      - assets:/opt/star-burger/assets
      - bundles:/opt/star-burger/bundles
    command: ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
    networks:
      - app-network
  
  backend:
    image: star_burger_backend
    container_name: star_burger_backend
    build: ../backend
    volumes:
      - assets:/opt/star-burger/assets
      - bundles:/opt/star-burger/bundles
      - ../media:/opt/star-burger/media
      - ../staticfiles:/opt/star-burger/staticfiles
    env_file:
      - ../.env
    ports:
      - 127.0.0.1:8000:8000
    command: gunicorn -w 5 -b 0.0.0.0:8000 star_burger.wsgi:application
    depends_on:
      - database
      - frontend
    networks:
      - app-network

volumes:
  postgres_data:
  assets:
  bundles:

networks:
  app-network:
    driver: bridge
    