# Generated by Django 3.2.15 on 2024-05-24 16:23

from django.db import migrations


class Migration(migrations.Migration):
    def add_price_to_order_products(apps, schema_editor):
        OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')

        for order_product in OrderProduct.objects.select_related('product').iterator():
            order_product.price = order_product.product.price
            order_product.save()

    dependencies = [
        ('foodcartapp', '0041_orderproduct_price'),
    ]

    operations = [
        migrations.RunPython(add_price_to_order_products)
    ]
