# Generated by Django 3.2.15 on 2024-05-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20240524_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=400, verbose_name='описание'),
        ),
    ]
